import { AreaWithScore, Review } from '@/types';

export const areas: AreaWithScore[] = [
  {
    id: '1',
    name: 'Agrabad Access Road',
    name_bn: 'আগ্রাবাদ এক্সেস রোড',
    slug: 'agrabad-access-road',
    parent_area: 'Agrabad',
    parent_area_bn: 'আগ্রাবাদ',
    city: 'Chittagong',
    city_bn: 'চট্টগ্রাম',
    latitude: 22.3252,
    longitude: 91.8123,
    created_at: '2024-01-01',
    scores: {
      area_id: '1',
      overall_score: 72,
      safety_score: 68,
      infrastructure_score: 65,
      livability_score: 70,
      accessibility_score: 85,
      total_ratings: 47,
      total_reviews: 23,
      updated_at: '2024-12-01',
    },
    ai_summary: 'আগ্রাবাদ এক্সেস রোড একটি ব্যস্ত বাণিজ্যিক এলাকা। যোগাযোগ ব্যবস্থা চমৎকার, সিএনজি ও রিকশা সহজলভ্য। তবে বর্ষাকালে জলাবদ্ধতা এবং দৈনিক ২-৩ ঘন্টা লোডশেডিং সাধারণ সমস্যা। দিনের বেলা নিরাপদ, তবে রাতে সতর্কতা প্রয়োজন।',
    best_for: ['চাকরিজীবী', 'ব্যবসায়ী', 'ব্যাচেলর'],
    not_ideal_for: ['ছোট বাচ্চা আছে এমন পরিবার', 'বয়স্ক মানুষ'],
    alerts: ['বর্ষায় জলাবদ্ধতা হয়', 'দৈনিক ২-৩ ঘন্টা লোডশেডিং'],
    good_things: ['সিএনজি সহজলভ্য', 'হাসপাতাল ৫ মিনিটে', 'বাজার কাছে', 'ব্যাংক ও অফিস কাছে'],
    problems: ['রাস্তায় যানজট', 'শব্দ দূষণ বেশি', 'পার্কিং সমস্যা'],
  },
  {
    id: '2',
    name: 'Nasirabad Housing',
    name_bn: 'নাসিরাবাদ হাউজিং',
    slug: 'nasirabad-housing',
    parent_area: 'Nasirabad',
    parent_area_bn: 'নাসিরাবাদ',
    city: 'Chittagong',
    city_bn: 'চট্টগ্রাম',
    latitude: 22.3567,
    longitude: 91.8234,
    created_at: '2024-01-01',
    scores: {
      area_id: '2',
      overall_score: 85,
      safety_score: 88,
      infrastructure_score: 82,
      livability_score: 90,
      accessibility_score: 80,
      total_ratings: 62,
      total_reviews: 31,
      updated_at: '2024-12-01',
    },
    ai_summary: 'নাসিরাবাদ হাউজিং চট্টগ্রামের অন্যতম সেরা আবাসিক এলাকা। শান্ত পরিবেশ, ভালো স্কুল এবং নিরাপদ রাস্তা এই এলাকার বৈশিষ্ট্য। পরিবারের জন্য আদর্শ। ভাড়া তুলনামূলক বেশি কিন্তু মানের সাথে সামঞ্জস্যপূর্ণ।',
    best_for: ['পরিবার', 'শিশুদের জন্য', 'বয়স্ক মানুষ', 'শান্ত পরিবেশ খুঁজছেন যারা'],
    not_ideal_for: ['কম বাজেটে থাকতে চান যারা'],
    alerts: [],
    good_things: ['খুব নিরাপদ এলাকা', 'ভালো স্কুল কাছে', 'শান্ত পরিবেশ', 'পরিষ্কার রাস্তা', 'ভালো প্রতিবেশী'],
    problems: ['ভাড়া বেশি', 'মূল রাস্তা থেকে একটু দূরে'],
  },
  {
    id: '3',
    name: 'Halishahar A Block',
    name_bn: 'হালিশহর এ ব্লক',
    slug: 'halishahar-a-block',
    parent_area: 'Halishahar',
    parent_area_bn: 'হালিশহর',
    city: 'Chittagong',
    city_bn: 'চট্টগ্রাম',
    latitude: 22.3412,
    longitude: 91.7923,
    created_at: '2024-01-01',
    scores: {
      area_id: '3',
      overall_score: 68,
      safety_score: 72,
      infrastructure_score: 58,
      livability_score: 70,
      accessibility_score: 72,
      total_ratings: 38,
      total_reviews: 18,
      updated_at: '2024-12-01',
    },
    ai_summary: 'হালিশহর এ ব্লক মধ্যবিত্ত পরিবারের জন্য উপযুক্ত এলাকা। ভাড়া তুলনামূলক কম এবং প্রতিবেশী বন্ধুত্বপূর্ণ। তবে বর্ষাকালে জলাবদ্ধতা একটি বড় সমস্যা। কিছু রাস্তার অবস্থা খারাপ।',
    best_for: ['মধ্যবিত্ত পরিবার', 'বাজেট ফ্রেন্ডলি'],
    not_ideal_for: ['বর্ষায় সমস্যা এড়াতে চান যারা'],
    alerts: ['বর্ষায় তীব্র জলাবদ্ধতা', 'কিছু রাস্তা খারাপ'],
    good_things: ['ভাড়া কম', 'প্রতিবেশী ভালো', 'বাজার কাছে'],
    problems: ['জলাবদ্ধতা সমস্যা', 'রাস্তা ভাঙা', 'লোডশেডিং বেশি'],
  },
  {
    id: '4',
    name: 'GEC Circle',
    name_bn: 'জিইসি সার্কেল',
    slug: 'gec-circle',
    parent_area: 'GEC',
    parent_area_bn: 'জিইসি',
    city: 'Chittagong',
    city_bn: 'চট্টগ্রাম',
    latitude: 22.3589,
    longitude: 91.8312,
    created_at: '2024-01-01',
    scores: {
      area_id: '4',
      overall_score: 78,
      safety_score: 75,
      infrastructure_score: 80,
      livability_score: 72,
      accessibility_score: 85,
      total_ratings: 55,
      total_reviews: 27,
      updated_at: '2024-12-01',
    },
    ai_summary: 'জিইসি সার্কেল চট্টগ্রামের একটি প্রাণবন্ত এলাকা। রেস্টুরেন্ট, শপিং মল এবং বিনোদনের সুযোগ প্রচুর। তরুণ প্রজন্মের কাছে জনপ্রিয়। যোগাযোগ ব্যবস্থা খুব ভালো। রাতের বেলাও বেশ সক্রিয় এলাকা।',
    best_for: ['তরুণ পেশাজীবী', 'ব্যাচেলর', 'শহুরে জীবনযাপন'],
    not_ideal_for: ['শান্ত পরিবেশ খুঁজছেন যারা', 'ছোট বাচ্চা আছে এমন পরিবার'],
    alerts: ['সন্ধ্যায় যানজট বেশি'],
    good_things: ['রেস্টুরেন্ট ও ক্যাফে প্রচুর', 'শপিং সুবিধা', 'পরিবহন সহজ', 'নাইটলাইফ'],
    problems: ['কোলাহলপূর্ণ', 'ভাড়া বেশি', 'পার্কিং সমস্যা'],
  },
  {
    id: '5',
    name: 'Khulshi',
    name_bn: 'খুলশী',
    slug: 'khulshi',
    parent_area: 'Khulshi',
    parent_area_bn: 'খুলশী',
    city: 'Chittagong',
    city_bn: 'চট্টগ্রাম',
    latitude: 22.3634,
    longitude: 91.8189,
    created_at: '2024-01-01',
    scores: {
      area_id: '5',
      overall_score: 82,
      safety_score: 85,
      infrastructure_score: 78,
      livability_score: 88,
      accessibility_score: 77,
      total_ratings: 44,
      total_reviews: 22,
      updated_at: '2024-12-01',
    },
    ai_summary: 'খুলশী চট্টগ্রামের প্রিমিয়াম আবাসিক এলাকাগুলোর একটি। পাহাড়ি পরিবেশ, সবুজ প্রকৃতি এবং নিরাপদ পরিবেশ এই এলাকার প্রধান আকর্ষণ। উচ্চ মধ্যবিত্ত ও উচ্চবিত্তদের পছন্দের এলাকা।',
    best_for: ['পরিবার', 'প্রকৃতিপ্রেমী', 'উচ্চ বাজেট আছে যাদের'],
    not_ideal_for: ['কম বাজেট', 'শহরের কেন্দ্রে থাকতে চান যারা'],
    alerts: [],
    good_things: ['সুন্দর পরিবেশ', 'নিরাপদ', 'কম শব্দ দূষণ', 'সবুজ এলাকা', 'ভালো স্কুল কাছে'],
    problems: ['ভাড়া অনেক বেশি', 'কিছু জায়গায় পরিবহন কম'],
  },
  {
    id: '6',
    name: 'Panchlaish',
    name_bn: 'পাঁচলাইশ',
    slug: 'panchlaish',
    parent_area: 'Panchlaish',
    parent_area_bn: 'পাঁচলাইশ',
    city: 'Chittagong',
    city_bn: 'চট্টগ্রাম',
    latitude: 22.3512,
    longitude: 91.8256,
    created_at: '2024-01-01',
    scores: {
      area_id: '6',
      overall_score: 76,
      safety_score: 78,
      infrastructure_score: 72,
      livability_score: 80,
      accessibility_score: 74,
      total_ratings: 36,
      total_reviews: 16,
      updated_at: '2024-12-01',
    },
    ai_summary: 'পাঁচলাইশ মধ্যবিত্ত পরিবারের জন্য চমৎকার একটি এলাকা। শান্ত পরিবেশ, ভালো প্রতিবেশী এবং যুক্তিসঙ্গত ভাড়া। স্কুল ও বাজার কাছে। নাসিরাবাদের তুলনায় ভাড়া কম কিন্তু সুবিধা প্রায় একই।',
    best_for: ['মধ্যবিত্ত পরিবার', 'চাকরিজীবী', 'শিক্ষার্থী'],
    not_ideal_for: ['অতি বিলাসবহুল জীবনযাপন'],
    alerts: [],
    good_things: ['শান্ত এলাকা', 'যুক্তিসঙ্গত ভাড়া', 'স্কুল কাছে', 'বাজার কাছে'],
    problems: ['কিছু রাস্তা সরু', 'পিক আওয়ারে যানজট'],
  },
  {
    id: '7',
    name: 'Muradpur',
    name_bn: 'মুরাদপুর',
    slug: 'muradpur',
    parent_area: 'Muradpur',
    parent_area_bn: 'মুরাদপুর',
    city: 'Chittagong',
    city_bn: 'চট্টগ্রাম',
    latitude: 22.3678,
    longitude: 91.8123,
    created_at: '2024-01-01',
    scores: {
      area_id: '7',
      overall_score: 70,
      safety_score: 72,
      infrastructure_score: 68,
      livability_score: 68,
      accessibility_score: 72,
      total_ratings: 29,
      total_reviews: 14,
      updated_at: '2024-12-01',
    },
    ai_summary: 'মুরাদপুর একটি জনবহুল এলাকা। হাসপাতাল খুব কাছে (চট্টগ্রাম মেডিকেল)। বাজেট ফ্রেন্ডলি ভাড়া। কিন্তু রাস্তা সবসময় ব্যস্ত এবং শব্দ দূষণ আছে।',
    best_for: ['স্বাস্থ্যসেবা কর্মী', 'মেডিকেল স্টুডেন্ট', 'বাজেট সীমিত যাদের'],
    not_ideal_for: ['শান্ত পরিবেশ খুঁজছেন যারা'],
    alerts: ['সবসময় যানজট', 'শব্দ দূষণ বেশি'],
    good_things: ['মেডিকেল কাছে', 'ভাড়া কম', 'সব ধরনের দোকান আছে'],
    problems: ['খুব ব্যস্ত এলাকা', 'পার্কিং নেই', 'রাস্তা সরু'],
  },
  {
    id: '8',
    name: 'Oxygen',
    name_bn: 'অক্সিজেন',
    slug: 'oxygen',
    parent_area: 'Oxygen',
    parent_area_bn: 'অক্সিজেন',
    city: 'Chittagong',
    city_bn: 'চট্টগ্রাম',
    latitude: 22.3456,
    longitude: 91.8345,
    created_at: '2024-01-01',
    scores: {
      area_id: '8',
      overall_score: 65,
      safety_score: 62,
      infrastructure_score: 60,
      livability_score: 65,
      accessibility_score: 73,
      total_ratings: 25,
      total_reviews: 12,
      updated_at: '2024-12-01',
    },
    ai_summary: 'অক্সিজেন মোড় থেকে শুরু হওয়া এই এলাকা বাজেট ফ্রেন্ডলি। তবে কিছু জায়গায় নিরাপত্তা উদ্বেগের বিষয়। ট্রান্সপোর্ট সুবিধা মোটামুটি ভালো। জলাবদ্ধতা সমস্যা আছে।',
    best_for: ['একদম কম বাজেট', 'সাময়িক থাকার জন্য'],
    not_ideal_for: ['পরিবার', 'নারী একা থাকলে'],
    alerts: ['কিছু জায়গায় নিরাপত্তা সমস্যা', 'জলাবদ্ধতা'],
    good_things: ['ভাড়া সস্তা', 'বাস সুবিধা আছে'],
    problems: ['নিরাপত্তা উদ্বেগ', 'জলাবদ্ধতা', 'রাস্তার অবস্থা খারাপ'],
  },
  {
    id: '9',
    name: 'Sholoshahar',
    name_bn: 'ষোলশহর',
    slug: 'sholoshahar',
    parent_area: 'Sholoshahar',
    parent_area_bn: 'ষোলশহর',
    city: 'Chittagong',
    city_bn: 'চট্টগ্রাম',
    latitude: 22.3723,
    longitude: 91.8201,
    created_at: '2024-01-01',
    scores: {
      area_id: '9',
      overall_score: 80,
      safety_score: 82,
      infrastructure_score: 78,
      livability_score: 82,
      accessibility_score: 78,
      total_ratings: 41,
      total_reviews: 20,
      updated_at: '2024-12-01',
    },
    ai_summary: 'ষোলশহর সেনানিবাস সংলগ্ন এলাকা হওয়ায় বেশ নিরাপদ। ভালো স্কুল, হাসপাতাল এবং শপিং সুবিধা কাছে। পরিবারের জন্য উপযুক্ত এলাকা। ক্যান্টনমেন্টের কারণে পরিবেশ শৃঙ্খলাবদ্ধ।',
    best_for: ['পরিবার', 'সরকারি চাকরিজীবী', 'সেনা পরিবার'],
    not_ideal_for: ['বাজেট খুব কম যাদের'],
    alerts: [],
    good_things: ['নিরাপদ এলাকা', 'শৃঙ্খলাবদ্ধ', 'ভালো স্কুল', 'মেমো হাসপাতাল কাছে'],
    problems: ['ভাড়া একটু বেশি', 'কিছু এলাকায় প্রবেশ সীমিত'],
  },
  {
    id: '10',
    name: 'Chandgaon',
    name_bn: 'চাঁদগাঁও',
    slug: 'chandgaon',
    parent_area: 'Chandgaon',
    parent_area_bn: 'চাঁদগাঁও',
    city: 'Chittagong',
    city_bn: 'চট্টগ্রাম',
    latitude: 22.3834,
    longitude: 91.8456,
    created_at: '2024-01-01',
    scores: {
      area_id: '10',
      overall_score: 67,
      safety_score: 68,
      infrastructure_score: 62,
      livability_score: 70,
      accessibility_score: 68,
      total_ratings: 33,
      total_reviews: 15,
      updated_at: '2024-12-01',
    },
    ai_summary: 'চাঁদগাঁও চট্টগ্রাম শহরের একটু বাইরের দিকে। ভাড়া তুলনামূলক কম এবং খোলামেলা পরিবেশ। তবে শহরের কেন্দ্র থেকে দূরে হওয়ায় যাতায়াতে সময় লাগে বেশি।',
    best_for: ['বাজেট ফ্রেন্ডলি', 'খোলামেলা পরিবেশ পছন্দ যারা'],
    not_ideal_for: ['শহরের কেন্দ্রে কাজ করেন যারা'],
    alerts: ['শহর থেকে দূরে'],
    good_things: ['ভাড়া কম', 'খোলামেলা পরিবেশ', 'কম জনবসতি'],
    problems: ['শহর থেকে দূরে', 'পরিবহন কম', 'কিছু সুবিধা নেই'],
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    area_id: '1',
    user_id: 'u1',
    content: 'আগ্রাবাদে ৩ বছর ধরে আছি। অফিস কাছে বলে সুবিধা। কিন্তু বর্ষায় একদম বের হওয়া যায় না, হাঁটু পানি উঠে যায়।',
    pros: ['অফিস কাছে', 'সিএনজি সহজ', 'বাজার কাছে'],
    cons: ['জলাবদ্ধতা', 'শব্দ দূষণ'],
    created_at: '2024-11-15',
    user: { is_verified: true },
  },
  {
    id: 'r2',
    area_id: '2',
    user_id: 'u2',
    content: 'নাসিরাবাদ হাউজিং সত্যিই অসাধারণ। বাচ্চাদের স্কুলে হেঁটে যেতে পারি। রাতে মহিলারাও নিরাপদে হাঁটতে পারে। একটু দামি কিন্তু worth it।',
    pros: ['নিরাপদ', 'স্কুল কাছে', 'শান্ত'],
    cons: ['ভাড়া বেশি'],
    created_at: '2024-11-20',
    user: { is_verified: true },
  },
  {
    id: 'r3',
    area_id: '4',
    user_id: 'u3',
    content: 'জিইসি তরুণদের জন্য বেস্ট! খাবার, শপিং সব আছে। তবে ফ্যামিলির জন্য একটু ব্যস্ত জায়গা।',
    pros: ['খাবারের জায়গা অনেক', 'শপিং', 'বন্ধুদের সাথে ঘুরতে ভালো'],
    cons: ['গোলমাল বেশি', 'পার্কিং নেই'],
    created_at: '2024-11-25',
    user: { is_verified: true },
  },
  {
    id: 'r4',
    area_id: '5',
    user_id: 'u4',
    content: 'খুলশীতে নতুন এসেছি। পাহাড়ের ধারে থাকার অনুভূতি অন্যরকম। সন্ধ্যায় বাতাস ভালো লাগে। তবে ভাড়া অনেক বেশি।',
    pros: ['প্রাকৃতিক সৌন্দর্য', 'শান্ত', 'নিরাপদ'],
    cons: ['ভাড়া অনেক বেশি', 'রিকশা কম পাওয়া যায়'],
    created_at: '2024-12-01',
    user: { is_verified: true },
  },
  {
    id: 'r5',
    area_id: '3',
    user_id: 'u5',
    content: 'হালিশহরে ভাড়া কম এটা ভালো। কিন্তু জুন-জুলাইতে একদম থাকা যায় না। ঘরে পানি ঢুকে যায়।',
    pros: ['ভাড়া কম', 'প্রতিবেশী ভালো'],
    cons: ['জলাবদ্ধতা ভয়াবহ', 'রাস্তা ভাঙা'],
    created_at: '2024-11-10',
    user: { is_verified: true },
  },
];

export function getAreaBySlug(slug: string): AreaWithScore | undefined {
  return areas.find(area => area.slug === slug);
}

export function getReviewsByAreaId(areaId: string): Review[] {
  return reviews.filter(review => review.area_id === areaId);
}

export function searchAreas(query: string): AreaWithScore[] {
  const lowerQuery = query.toLowerCase();
  return areas.filter(area =>
    area.name.toLowerCase().includes(lowerQuery) ||
    area.name_bn.includes(query) ||
    area.parent_area.toLowerCase().includes(lowerQuery) ||
    area.parent_area_bn.includes(query)
  );
}
